blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/bingxueshuang/iskios/discussions
    about: Ask questions and discuss with other users in GitHub itself.
